export const karlotto = [
    'Ein Loch ist im Eimer, Karl-Otto, Karl-Otto',
    'Ein Loch ist im Eimer, Karl-Otto - Ein Loch!',
    'Verstopf\' es, oh Henry, oh Henry, oh Henry',
    'Verstopf\' es, oh Henry, oh Henry - mach\'s dicht!',
    'Womit denn, Karl-Otto, Karl-Otto, Karl-Otto',
    'Womit denn, Karl-Otto, Karl-Otto, womit?',
    'Mit Stroh, oh Henry, oh Henry, oh Henry',
    'Mit Stroh, oh Henry, oh Henry - mit Stroh',
    'Das Stroh ist zu lang, Karl-Otto, Karl-Otto',
    'Das Stroh ist zu lang, Karl-Otto, zu lang',
    'Dann kürz\' es, oh Henry, oh Henry, oh Henry',
    'Dann kürz\' es, oh Henry - Mensch, hack\'s ab!',
    'Womit denn, Karl-Otto, Karl-Otto, Karl-Otto',
    'Womit denn, Karl-Otto, Karl-Otto, womit?',
    'Mit \'ner Axt, oh Henry, oh Henry, oh Henry',
    'Mit \'ner Axt, oh Henry, oh Henry, mit \'ner Axt',
    'Die Axt ist zu stumpf, Karl-Otto, Karl-Otto',
    'Die Axt ist zu stumpf, Karl-Otto - zu stumpf',
    'Dann schärf\' sie, oh Henry, oh Henry, oh Henry',
    'Dann schärf\' sie, oh Henry - mach sie scharf!',
    'Womit denn, Karl-Otto, Karl-Otto, Karl-Otto',
    'Womit denn, Karl-Otto, Karl-Otto, womit?',
    'Mit \'nem Stein, oh Henry, oh Henry, oh Henry',
    'Mit \'nem Stein, oh Henry, oh Henry - mit\'m Stein',
    'Der Stein ist zu trocken, Karl-Otto, Karl-Otto',
    'Der Stein ist zu trocken, Karl-Otto - zu trocken',
    'Hol\' Wasser, oh Henry, oh Henry, oh Henry',
    'Hol\' Wasser, oh Henry, oh Henry - hol\' Wasser!',
    'Worin denn, Karl-Otto, Karl-Otto, Karl-Otto',
    'Worin denn, Karl-Otto, Karl-Otto, worin?',
    'Im Eimer, oh Henry, oh Henry, oh Henry',
    'Im Eimer, oh Henry, oh Henry - im Eimer!'
];
