import { BrowserModule } from '@angular/platform-browser';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NgModule } from '@angular/core';
import {
  DefaultInputComponent,
  DefaultOutputComponent,
  DynamicFieldComponent,
  FieldHostDirective,
  FilterComponent,
  FormComponent,
  GroupPipe,
  InputComponent,
  InputErrorsComponent,
  ListComponent,
  ListHeaderComponent,
  ListItemsComponent,
  LoaderComponent,
  LoaderService,
  LoginComponent,
  MenuComponent,
  MockupComponent,
  OutputComponent,
  PaginationComponent,
  PopComponent,
  SelectComponent,
  TabComponent,
  TabsComponent,
} from './index';

@NgModule({
  entryComponents: [
    InputComponent,
    PopComponent,
    DynamicFieldComponent,
    DefaultInputComponent,
    DefaultOutputComponent,
    SelectComponent,
    LoaderComponent,
  ],
  declarations: [
    ListComponent,
    PaginationComponent,
    TabsComponent,
    TabComponent,
    MockupComponent,
    FilterComponent,
    InputComponent,
    OutputComponent,
    ListItemsComponent,
    ListHeaderComponent,
    GroupPipe,
    InputErrorsComponent,
    FormComponent,
    PopComponent,
    MenuComponent,
    SelectComponent,
    LoginComponent,
    FieldHostDirective,
    DynamicFieldComponent,
    DefaultInputComponent,
    DefaultOutputComponent,
    LoaderComponent,
  ],
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
  ],
  exports: [
    ReactiveFormsModule,
    ListComponent,
    PaginationComponent,
    TabsComponent,
    TabComponent,
    MockupComponent,
    FilterComponent,
    InputComponent,
    OutputComponent,
    ListItemsComponent,
    ListHeaderComponent,
    GroupPipe,
    FormComponent,
    PopComponent,
    MenuComponent,
    SelectComponent,
    LoginComponent,
    InputErrorsComponent,
    LoaderComponent,
  ],
  providers: [
    LoaderService,
  ],
})
export class UiModule {
}