conventional-changelog -p angular -l core -s -i packages/core/CHANGELOG.md --commit-path packages/core
conventional-changelog -p angular -l calendar -s -i packages/calendar/CHANGELOG.md --commit-path packages/calendar
conventional-changelog -p angular -l ui -s -i packages/ui/CHANGELOG.md --commit-path packages/ui
conventional-changelog -p angular -l data -s -i packages/data/CHANGELOG.md --commit-path packages/data
conventional-changelog -p angular -l tinymce -s -i packages/tinymce/CHANGELOG.md --commit-path packages/tinymce
conventional-changelog -p angular -l medium-editor -s -i packages/medium-editor/CHANGELOG.md --commit-path packages/medium-editor
conventional-changelog -p angular -l location -s -i packages/location/CHANGELOG.md --commit-path packages/location
conventional-changelog -p angular -l style -s -i packages/style/CHANGELOG.md --commit-path packages/style
conventional-changelog -p angular -l ace -s -i packages/ace/CHANGELOG.md --commit-path packages/ace