sh scripts/changelog-package.sh core
sh scripts/changelog-package.sh calendar
sh scripts/changelog-package.sh ui
sh scripts/changelog-package.sh data
sh scripts/changelog-package.sh tinymce
sh scripts/changelog-package.sh medium-editor
sh scripts/changelog-package.sh location
sh scripts/changelog-package.sh style
sh scripts/changelog-package.sh ace