export const songs = {
  name: 'Jazz 1300',
  songs: [
    {
      title: '26-2',
      composer: 'Coltrane John',
      style: 'Medium Up Swing',
      key: 'F',
      transpose: null,
      music: {
        raw:
          '*A[T44F^7 Ab7LZDb^7 E7LZA^7 C7LZC-7 F7LZBb^7 Db7LZGb^7 A7LZD-7 G7LZG-7 C7 ]*A[F^7 Ab7LZDb^7 E7LZA^7 C7LZC-7 F7LZBb^7 Ab7LZDb^7 E7LZA^7 C7LZF^7XyQ]*B[C-7 F7LZE-7 A7LZD^7 F7LZBb^7XyQ|Eb-7XyQ|Ab7XyQ|Db^7XyQ|G-7 C7 ]*A[F^7 Ab7LZDb^7 E7LZA^7 C7LZC-7 F7LZBb^7 Ab7LZDb^7 E7LZA^7 C7LZF^7   Z',
        timeSignature: 'T44',
        measures: [
          ['F^7', 'Ab7'],
          ['Db^7', 'E7'],
          ['A^7', 'C7'],
          ['C-7', 'F7'],
          ['Bb^7', 'Db7'],
          ['Gb^7', 'A7'],
          ['D-7', 'G7'],
          ['G-7', 'C7'],
          ['F^7', 'Ab7'],
          ['Db^7', 'E7'],
          ['A^7', 'C7'],
          ['C-7', 'F7'],
          ['Bb^7', 'Ab7'],
          ['Db^7', 'E7'],
          ['A^7', 'C7'],
          ['F^7'],
          ['C-7', 'F7'],
          ['E-7', 'A7'],
          ['D^7', 'F7'],
          ['Bb^7'],
          ['Eb-7'],
          ['Ab7'],
          ['Db^7'],
          ['G-7', 'C7'],
          ['F^7', 'Ab7'],
          ['Db^7', 'E7'],
          ['A^7', 'C7'],
          ['C-7', 'F7'],
          ['Bb^7', 'Ab7'],
          ['Db^7', 'E7'],
          ['A^7', 'C7'],
          ['F^7'],
        ],
      },
      compStyle: '0',
      bpm: null,
      repeats: null,
    },
    {
      title: '500 Miles High',
      composer: 'Corea Chick',
      style: 'Bossa Nova',
      key: 'E-',
      transpose: null,
      music: {
        raw:
          '[T44E-7XyQKcl LZG-7XyQKcl LZBb^7XyQKcl LZBh7XyQ|E7#9XyQ|A-7XyQKcl LZF#h7XyQKcl LZF-7XyQKcl QLZC-7XyQKcl LZB7#9XyQKcl  ZXyQXyQ  Y{QC-7XyQKcl LZAb^7XyQKcl  }',
        timeSignature: 'T44',
        measures: [
          ['E-7'],
          ['E-7'],
          ['G-7'],
          ['G-7'],
          ['Bb^7'],
          ['Bb^7'],
          ['Bh7'],
          ['E7#9'],
          ['A-7'],
          ['A-7'],
          ['F#h7'],
          ['F#h7'],
          ['F-7'],
          ['F-7'],
          ['C-7'],
          ['C-7'],
          ['B7#9'],
          ['B7#9'],
          ['C-7'],
          ['C-7'],
          ['Ab^7'],
          ['Ab^7'],
        ],
      },
      compStyle: '0',
      bpm: null,
      repeats: null,
    },
    {
      title: '502 Blues',
      composer: 'Rowles Jimmy',
      style: 'Waltz',
      key: 'A-',
      transpose: null,
      music: {
        raw:
          '{T34A-7XyQ|Db^7XyQ|Bh7XyQ|E7#9XyQ|A-7XyQ|Db^7XyQ|Bh7XyQ|E7#9XyQ|C-7XyQ|F7b9XyQ|Bb^7XyQ|Ab-7 Db7LZN1F#h7XyQ|B7b9XyQ|E^7#5XyQ|E^7#5 E7 }|N2F#h7XyQ|B7b9XyQ|E-7XyQKcl  Z',
        timeSignature: 'T44',
        measures: [
          ['A-7'],
          ['Db^7'],
          ['Bh7'],
          ['E7#9'],
          ['A-7'],
          ['Db^7'],
          ['Bh7'],
          ['E7#9'],
          ['C-7'],
          ['F7b9'],
          ['Bb^7'],
          ['Ab-7', 'Db7'],
          ['F#h7'],
          ['B7b9'],
          ['E^7#5'],
          ['E^7#5', 'E7'],
          ['F#h7'],
          ['B7b9'],
          ['E-7'],
          ['E-7'],
        ],
      },
      compStyle: '0',
      bpm: null,
      repeats: null,
    },
    {
      title: '52nd Street Theme',
      composer: 'Monk Thelonious',
      style: 'Up Tempo Swing',
      key: 'C',
      transpose: null,
      music: {
        raw:
          '{*AT44C A-7LZD-7 G7LZC A-7LZD-7 G7LZC A-7LZD-7 G7LZC G7LZCXyQ}[*BC7,XyQKcl LZF6XyQKcl LZD7,XyQKcl LZG7XyQKcl  ][*AC, A-7LZD-7 G7LZC A-7LZD-7 G7LZC A-7LZD-7 G7LZC G7LZCXyQZ ',
        timeSignature: 'T44',
        measures: [
          ['C', 'A-7'],
          ['D-7', 'G7'],
          ['C', 'A-7'],
          ['D-7', 'G7'],
          ['C', 'A-7'],
          ['D-7', 'G7'],
          ['C', 'G7'],
          ['C'],
          ['C7'],
          ['C7'],
          ['F6'],
          ['F6'],
          ['D7'],
          ['D7'],
          ['G7'],
          ['G7'],
          ['C', 'A-7'],
          ['D-7', 'G7'],
          ['C', 'A-7'],
          ['D-7', 'G7'],
          ['C', 'A-7'],
          ['D-7', 'G7'],
          ['C', 'G7'],
          ['C'],
        ],
      },
      compStyle: '0',
      bpm: null,
      repeats: null,
    },
    {
      title: '9.20 Special',
      composer: 'Warren Earl',
      style: 'Medium Swing',
      key: 'C',
      transpose: null,
      music: {
        raw:
          '{*AT44C9,XyQ|Eb-6,XyQ|C9,XyQ|Eb-6XyQ|Bb,XyQ|sBb7,A7,Ab7,G7|N1lC9, F#o7,LZC9, sAb7,G7}XyQXyQ LZN2lC9, F#o7LZlC9, sF7,Bb][*BlBb,XyQ|Eb, Eb6LZEb6,XyQKcl LZG9,XyQ|F, F6,LZF9,XyQ|  F7 ][*AC9,XyQ|Eb-6,XyQ|C9,XyQ|Eb-6,XyQ|Bb,XyQ|sBb7,A7,Ab7,G7|lC9, F#o7 ,|sC6,F7,Bb,D9Z ',
        timeSignature: 'T44',
        measures: [
          ['C9'],
          ['Eb-6'],
          ['C9'],
          ['Eb-6'],
          ['Bb'],
          ['Bb7', 'A7', 'Ab7', 'G7'],
          ['C9', 'F#o7'],
          ['C9', 'Ab7', 'G7'],
          ['C9', 'F#o7'],
          ['C9', 'F7', 'Bb'],
          ['Bb'],
          ['Eb', 'Eb6'],
          ['Eb6'],
          ['Eb6'],
          ['G9'],
          ['F', 'F6'],
          ['F9'],
          ['F7'],
          ['C9'],
          ['Eb-6'],
          ['C9'],
          ['Eb-6'],
          ['Bb'],
          ['Bb7', 'A7', 'Ab7', 'G7'],
          ['C9', 'F#o7'],
          ['C6', 'F7', 'Bb', 'D9'],
        ],
      },
      compStyle: '0',
      bpm: null,
      repeats: null,
    },
    {
      title: 'A Felicidade',
      composer: 'Jobim Antonio-Carlos',
      style: 'Bossa Nova',
      key: 'A-',
      transpose: null,
      music: {
        raw:
          '*A{T44A-7(C^7)XyQKcl LZC^7XyQKcl LZE-7XyQ|B7b9XyQ|E-7 <(Repeat Optional)>A7LZD-7 G7 }[*BC^7XyQKcl LZBh7XyQ|E7b9XyQ|A-7XyQKcl (Ab-7)LZG-7XyQ|C7XyQ|F^7XyQ|D-7XyQ|A-7XyQ|D7XyQ|A-7XyQ|Bh7 E7b9LZA-7XyQ|G7XyQ]*C[C^7LZF7LZC^7LZxLZG-7LZC7LZF^7LZxLZD-7LZG7LZC^7LZxLZF#h7LZB7b9LZsE-7,A7,|D-7,G7,]*D[lA-7XyQ|A-7/GXyQ|D7/F#XyQ|D-7/FXyQ|A-7XyQ|Bh7 E7b9LZA-7XyQKcl  Z ',
        timeSignature: 'T44',
        measures: [
          ['A-7', 'C^7'],
          ['A-7', 'C^7'],
          ['C^7'],
          ['C^7'],
          ['E-7'],
          ['B7b9'],
          ['E-7', 'A7'],
          ['D-7', 'G7'],
          ['C^7'],
          ['C^7'],
          ['Bh7'],
          ['E7b9'],
          ['A-7'],
          ['A-7'],
          ['G-7'],
          ['C7'],
          ['F^7'],
          ['D-7'],
          ['A-7'],
          ['D7'],
          ['A-7'],
          ['Bh7', 'E7b9'],
          ['A-7'],
          ['G7'],
          ['C^7'],
          ['F7'],
          ['C^7'],
          ['C^7'],
          ['G-7'],
          ['C7'],
          ['F^7'],
          ['F^7'],
          ['D-7'],
          ['G7'],
          ['C^7'],
          ['C^7'],
          ['F#h7'],
          ['B7b9'],
          ['E-7', 'A7'],
          ['D-7', 'G7'],
          ['A-7'],
          ['A-7/G'],
          ['D7/F#'],
          ['D-7/F'],
          ['A-7'],
          ['Bh7', 'E7b9'],
          ['A-7'],
          ['A-7'],
        ],
      },
      compStyle: '0',
      bpm: null,
      repeats: null,
    },
    {
      title: 'Ac-Cent-Tchu-Ate The Positive',
      composer: 'Arlen Harold',
      style: 'Medium Swing',
      key: 'F',
      transpose: null,
      music: {
        raw:
          '{*AT44F^7 F+LZF6 F^7LZG-7XyQ|C7XyQ||F^7 F+LZF6 F^7LZG-7 C7LZF6 C7 }[*BF6XyQ|F7XyQ|Bb^7 sG-7,C7,|lF6 C7LZF6XyQ|D7b9XyQ|G7#5XyQ|C7XyQ][*AF^7 F+LZF6 F^7LZG-7XyQ|C7XyQ||F^7 F+LZF6 F^7LZG-7 C7,LZF6 C7 Z ',
        timeSignature: 'T44',
        measures: [
          ['F^7', 'F+'],
          ['F6', 'F^7'],
          ['G-7'],
          ['C7'],
          ['F^7', 'F+'],
          ['F6', 'F^7'],
          ['G-7', 'C7'],
          ['F6', 'C7'],
          ['F6'],
          ['F7'],
          ['Bb^7', 'G-7', 'C7'],
          ['F6', 'C7'],
          ['F6'],
          ['D7b9'],
          ['G7#5'],
          ['C7'],
          ['F^7', 'F+'],
          ['F6', 'F^7'],
          ['G-7'],
          ['C7'],
          ['F^7', 'F+'],
          ['F6', 'F^7'],
          ['G-7', 'C7'],
          ['F6', 'C7'],
        ],
      },
      compStyle: '0',
      bpm: null,
      repeats: null,
    },
    {
      title: 'Across The Valley From The Alamo',
      composer: 'Greene Joe',
      style: 'Medium Swing',
      key: 'F',
      transpose: null,
      music: {
        raw:
          '{*AT44F^7,XyQKcl LZ x LZ x LZC7,XyQKcl LZN1G-7, C7,LZF^7,XyQ}XyQXyQ LZN2G-7, C7,LZF^7,XyQ]Y[*BBb^7,XyQ|F^7,XyQ|Bb^7, Bb-7,LZF^7,XyQ|A7,XyQ|D-7, G7,LZG7,XyQ|C7,XyQ]Y[*AF^7,XyQKcl LZ x LZ x LZC7,XyQKcl LZG-7, C7,LZF^7XyQZ ',
        timeSignature: 'T44',
        measures: [
          ['F^7'],
          ['F^7'],
          ['F^7'],
          ['F^7'],
          ['C7'],
          ['C7'],
          ['G-7', 'C7'],
          ['F^7'],
          ['G-7', 'C7'],
          ['F^7'],
          ['Bb^7'],
          ['F^7'],
          ['Bb^7', 'Bb-7'],
          ['F^7'],
          ['A7'],
          ['D-7', 'G7'],
          ['G7'],
          ['C7'],
          ['F^7'],
          ['F^7'],
          ['F^7'],
          ['F^7'],
          ['C7'],
          ['C7'],
          ['G-7', 'C7'],
          ['F^7'],
        ],
      },
      compStyle: '0',
      bpm: null,
      repeats: null,
    },
    {
      title: "Adam's Apple",
      composer: 'Shorter Wayne',
      style: 'Even 8ths',
      key: 'Ab',
      transpose: null,
      music: {
        raw:
          '[T44Ab7XyQKcl LZ x LZ x LZ x LZ x LZ x LZ x LZGb7XyQKcl LZ x LZ x LZAb7XyQKcl LZ x LZ x LZAb-7XyQ|Db7XyQ|Bb-7XyQ|Eb7#9XyQ|Ab7XyQKcl LZ x LZ x  Z',
        timeSignature: 'T44',
        measures: [
          ['Ab7'],
          ['Ab7'],
          ['Ab7'],
          ['Ab7'],
          ['Ab7'],
          ['Ab7'],
          ['Ab7'],
          ['Ab7'],
          ['Gb7'],
          ['Gb7'],
          ['Gb7'],
          ['Gb7'],
          ['Ab7'],
          ['Ab7'],
          ['Ab7'],
          ['Ab7'],
          ['Ab-7'],
          ['Db7'],
          ['Bb-7'],
          ['Eb7#9'],
          ['Ab7'],
          ['Ab7'],
          ['Ab7'],
          ['Ab7'],
        ],
      },
      compStyle: '0',
      bpm: null,
      repeats: null,
    },
    {
      title: 'African Queen, The',
      composer: 'Silver Horace',
      style: 'Latin',
      key: 'C-',
      transpose: null,
      music: {
        raw:
          '[*AT44C-9 Db9LZ x LZXyQr|XyQLZC-9, Db9LZ x LZXyQr|XyQ ][*AC-9 Db9LZ x LZXyQr|XyQLZC-9, Db9LZ x LZXyQr|XyQ ][*BBb7 A7LZAb7 G7LZC-9 Db9LZ x LZC-9, Db9LZ x  Z ',
        timeSignature: 'T44',
        measures: [
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
          ['Bb7', 'A7'],
          ['Ab7', 'G7'],
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
          ['C-9', 'Db9'],
        ],
      },
      compStyle: '0',
      bpm: null,
      repeats: null,
    },
    {
      title: 'Afro Blue',
      composer: 'Santamaria Mongo',
      style: 'Waltz',
      key: 'F-',
      transpose: null,
      music: {
        raw:
          '[T34F-7XyQ|G-7XyQ|Ab^7 G-7LZF-7XyQ|F-7XyQ|G-7XyQ|Ab^7 G-7LZF-7XyQ|EbXyQKcl LZDb EbLZF-7XyQ|EbXyQKcl LZDb EbLZF-7   Z',
        timeSignature: 'T44',
        measures: [
          ['F-7'],
          ['G-7'],
          ['Ab^7', 'G-7'],
          ['F-7'],
          ['F-7'],
          ['G-7'],
          ['Ab^7', 'G-7'],
          ['F-7'],
          ['Eb'],
          ['Eb'],
          ['Db', 'Eb'],
          ['F-7'],
          ['Eb'],
          ['Eb'],
          ['Db', 'Eb'],
          ['F-7'],
        ],
      },
      compStyle: '0',
      bpm: null,
      repeats: null,
    },
    {
      title: 'Afro Centric',
      composer: 'Henderson Joe',
      style: 'Up Tempo Swing',
      key: 'Db',
      transpose: null,
      music: {
        raw:
          '[T44Db^7#11XyQKcl LZ x LZ x LZC-7XyQKcl LZ x LZ x LZDb^7#11XyQKcl LZ x LZ x LZAb^7#11XyQKcl LZ x LZ x LZGb^7#11XyQKcl LZ x LZ x LZF-7XyQ|Gb^7#11XyQ|F-7XyQ|Gb^7#11XyQ|Gh7XyQ|C^7#11   Z',
        timeSignature: 'T44',
        measures: [
          ['Db^7#11'],
          ['Db^7#11'],
          ['Db^7#11'],
          ['Db^7#11'],
          ['C-7'],
          ['C-7'],
          ['C-7'],
          ['C-7'],
          ['Db^7#11'],
          ['Db^7#11'],
          ['Db^7#11'],
          ['Db^7#11'],
          ['Ab^7#11'],
          ['Ab^7#11'],
          ['Ab^7#11'],
          ['Ab^7#11'],
          ['Gb^7#11'],
          ['Gb^7#11'],
          ['Gb^7#11'],
          ['Gb^7#11'],
          ['F-7'],
          ['Gb^7#11'],
          ['F-7'],
          ['Gb^7#11'],
          ['Gh7'],
          ['C^7#11'],
        ],
      },
      compStyle: '0',
      bpm: null,
      repeats: null,
    },
    {
      title: 'After You',
      composer: 'Porter Cole',
      style: 'Ballad',
      key: 'C',
      transpose: null,
      music: {
        raw:
          '[*AT44C^7XyQ|G7b9XyQ|C^7 G7#5LZC^7 E7#5LZA-7XyQ|D7XyQ|D-7XyQ|G7b9XyQ|C^7XyQ|G7b9XyQ|C^7 G7#5LZC^7 E7#5LZA-7XyQ|D7XyQ[*BG^7XyQ|D7b9XyQ|G-7XyQ|C7XyQ|F^7 C7b9LZF69XyQ|F-7XyQ|Bb9XyQ|D-7b5XyQ|G7b9XyQ][*CC^7XyQ|G7b9XyQ|C^7 A7LZD-7 F-6LZE-7 A-7LZD7 G7LZC69XyQKcl  Z ',
        timeSignature: 'T44',
        measures: [
          ['C^7'],
          ['G7b9'],
          ['C^7', 'G7#5'],
          ['C^7', 'E7#5'],
          ['A-7'],
          ['D7'],
          ['D-7'],
          ['G7b9'],
          ['C^7'],
          ['G7b9'],
          ['C^7', 'G7#5'],
          ['C^7', 'E7#5'],
          ['A-7'],
          ['D7'],
          ['G^7'],
          ['D7b9'],
          ['G-7'],
          ['C7'],
          ['F^7', 'C7b9'],
          ['F69'],
          ['F-7'],
          ['Bb9'],
          ['D-7b5'],
          ['G7b9'],
          ['C^7'],
          ['G7b9'],
          ['C^7', 'A7'],
          ['D-7', 'F-6'],
          ['E-7', 'A-7'],
          ['D7', 'G7'],
          ['C69'],
          ['C69'],
        ],
      },
      compStyle: '0',
      bpm: null,
      repeats: null,
    },
  ],
};
